name: Lint, Test, Build

on:
  pull_request:
    branches:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install
        run: yarn install --immutable --immutable-cache --check-cache

      - name: Lint
        run: yarn run lint

      - name: Build
        run: yarn run build

      - name: Test
        run: yarn run test
